Assignment/WebApplication1/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.DataAccess.Interfaces;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles ="ADMIN")]
    public class AdminController : Controller
    {
        private readonly ICacheRepository _cacheRepo;
        private readonly IRidesRepository _ridesRepo;
        public AdminController (ICacheRepository cacheRepo)
        {
            _cacheRepo = cacheRepo;
        }
        
        [HttpPost]
        public IActionResult Check(Category c)
        {
            _cacheRepo.UpsertCategory(c);
            return View();
        }

        public IActionResult Index()
        {
            var list = _ridesRepo.GetRides();
            return View();
        }
        
    }
}

Assignment/WebApplication1/Controllers/DriverController.cs
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.DataAccess.Interfaces;
using WebApplication1.Models;
using WebApplication1.Models.Domain;

namespace WebApplication1.Controllers
{
    [Authorize(Roles ="DRIVER")]
    public class DriverController : Controller
    {
        private readonly IDriversRepository _driversRepo;
        private readonly IConfiguration _config;
        private readonly IPubSubRepository _pubsubRepo;
        public DriverController(IDriversRepository driversRepo, IConfiguration config, IPubSubRepository pubsubRepo)
        {
            _config = config;
            _driversRepo = driversRepo;
            _pubsubRepo = pubsubRepo;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Index()
        {
            
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(IFormFile logo, Driver d)
        {
            try
            {
                string bucketName = _config.GetSection("AppSettings").GetSection("BucketName").Value;
                string uniqueFilename = Guid.NewGuid() + System.IO.Path.GetExtension(logo.FileName);

                //upload file to cloud storage
                var storage = StorageClient.Create();

                using (var myStream = logo.OpenReadStream())
                {
                    storage.UploadObject(bucketName, uniqueFilename, null, myStream);
                }

                //add a reference to the file url with the instance of the blog >>> b
                d.Photo = $"https://storage.googleapis.com/{bucketName}/{uniqueFilename}";

                //save everything in db
                _driversRepo.AddDriver(d);
               
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Driver wasn't created successfully";
                return View(d);
            }
        }
    }
}

Assignment/WebApplication1/Controllers/PassengerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.DataAccess.Interfaces;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "PASSENGER")]
    public class PassengerController : Controller
    {
        private readonly ICacheRepository _cacheRepo;
        public PassengerController(ICacheRepository cacheRepo)
        {
            _cacheRepo = cacheRepo;
        }

        public IActionResult Create()
        {
            return View();
        }

        
    }
}

Assignment/WebApplication1/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class RolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public RolesController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult AllocateRole()
        {
            return View(); 
        }
        
        [HttpPost]
        public async Task<IActionResult> AllocateRole(string role)
        {
            if(role == "DRIVER" || role == "PASSENGER")
            {
                var currentLoggedInUser = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                await _userManager.AddToRoleAsync(currentLoggedInUser, role);
            }           
            return View();
        }
    }
}

Assignment/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taxi App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Taxi App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.Name != null)
                        {

                            if (User.IsInRole("ADMIN"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Check">Edit Pricing</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Confirmed Bookings</a>
                                </li>
                            }

                            else if (User.IsInRole("DRIVER"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Create">Create Driver</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">See Available Bookings</a>
                                </li>
                            }

                            else if (User.IsInRole("PASSENGER"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="Create">Create Ride</a>
                                </li>
                            }

                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="AllocateRole">Choose Role</a>
                                </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @if (TempData["error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["error"]
                </div>
            }

            @if (TempData["message"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["message"]
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>